name: Playwright tests with Allure reports wo peaceiris

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Set a timestamp
      id: timestampid
      run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17 
             
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Deploy to GitHub Pages
      run: |
        # Configure Git
        git config --global --add safe.directory /__w/playwright/playwright
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy Playwright report1"
        # Switch to gh-pages branch
        git fetch origin
        git add .
        git commit -m "Deploy Playwright report2"
        git checkout gh-pages || git checkout --orphan gh-pages
        git add .
        git commit -m "Deploy Playwright report"
        git pull origin gh-pages
        # Copy the Playwright report to the gh-pages branch
       
        mkdir -p reports/${{ steps.timestampid.outputs.timestamp }}
        cp -r allure-report/* reports/${{ steps.timestampid.outputs.timestamp }}/
        
        # Commit and push changes
        git add .
        git commit -m "Deploy Playwright report"
        git push -f origin gh-pages
    - name: Write URL in summary
      run: echo "### Test results - https://${{ github.repository_owner }}.github.io/playwright/reports/${{ steps.timestampid.outputs.timestamp }}/index.html" >> $GITHUB_STEP_SUMMARY
